sudo: required
services:
  - docker

before_install:
  - docker build -t testme -f Dockerfile.dev .

script:
  - docker run testme npm run test --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-React"
  env: "DockerReact-env"
  bucket_name: "/elasticbeanstalk-us-east-1-600270412190"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
